escolaWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('secretaria.urls', namespace='secretaria')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exercicios/', include('exercicios.urls',namespace='exercicios')),
    
]

exercicios/urls.py
from django.urls import path
from .views import PadraoView, ExerciciosView, ResumoExerciciosView, ExercicioInstanceByUserListView

app_name='exercicios'

urlpatterns = [
    path('', PadraoView.as_view(), name='inicial'),
    path('questoes/',ResumoExerciciosView.as_view(), name='resumo'),
    #path('questoes/',ExercicioInstanceByUserListView.as_view(), name='resumo'),
    path('questoes/<int:id>', ExerciciosView.as_view(), name='questoes'),
]

users/urls.py
from django.urls import path
from .views import PadraoView

app_name = 'users'

urlpatterns = [
    path('', PadraoView.as_view(), name='perfil'),
    
]

exercicios/models.py
import uuid # Required for unique exercises
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from users.models import User
import datetime
from django.utils import timezone
from django.db.models.signals import post_save #, pre_save


class Materia(models.Model):
    """Modelo representando a materia do exercício."""
    name = models.CharField(max_length=200, help_text='Escreva o nome da matéria')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Exercicios(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    enunciado = models.CharField(max_length=500)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    professor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    pub_date = models.DateTimeField('date published',null=True, blank=True)
    is_active = models.BooleanField(default=True)
    until_date = models.DateTimeField(null=True, blank=True)
    #until_date = models.DateTimeField('date published', help_text='Até quando esse exercício deverá ser entregue')

        # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    #materia = models.ManyToManyField(Materia, help_text='Selecione a materia desse exercício')
    materia = models.ForeignKey('Materia', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.enunciado

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=30)
    
    def get_answer(self):
        return self.respostas_set.all()
    
    @property
    def active(self):
        if self.until_date and datetime.date.today() > self.until_date:
            return False
        return True
        
    #def display_materia(self):
    #    """Create a string for the Materia. This is required to display materia in Admin."""
    #    return ', '.join(materia.name for materia in self.materia.all()[:3])

    #display_materia.short_description = 'Materia'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this exercise."""
        return reverse('exercicio-detail', args=[str(self.id)])







class Respostas(models.Model):
    exercicio = models.ForeignKey(Exercicios, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)
    resposta_texto = models.CharField(max_length=200)
    def __str__(self):
        """String for representing the Model object."""
        return self.resposta_texto
    

class ExercicioInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='ID unico desse exercício')
    exercicio = models.ForeignKey('Exercicios', on_delete=models.RESTRICT, null=True)
    until_date = models.DateField(null=True, blank=True)
    aluno = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    alternativa = models.ForeignKey('Respostas', on_delete=models.RESTRICT, null=True)
    answer_date = models.DateField(null=True, blank=True) 
    acertou = models.BooleanField(null=True)

    LOAN_STATUS = (
        ('a', 'Acerto'),
        ('e', 'Erro'),
        ('n', 'Não Respondido'),
        ('t', 'Atrasado'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='n',
        help_text='Status do exercício',
    )

    class Meta:
        ordering = ['until_date']

    def __str__(self):
        """String for representing the Model object."""
        return self.exercicio.enunciado
    
    @property
    def is_late(self):
        if self.until_date and datetime.date.today() > self.until_date:
            return True
        return False
    
def save_post(sender, instance, **kwargs):
    
    alunos = User.objects.all()
    for atual in alunos:
        exercicio_novo = ExercicioInstance()
        exercicio_novo.exercicio = instance
        exercicio_novo.until_date = instance.until_date
        exercicio_novo.aluno = atual
        exercicio_novo.status = 'n'
        exercicio_novo.save()

     
post_save.connect(save_post, sender=Exercicios)

exercicios/views.py
from django.shortcuts import render,redirect #, get_object_or_404
#from django.http import HttpResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from .models import Exercicios, ExercicioInstance, Materia, ExercicioInstance, Respostas
from users.models import User
from django.db.models import Q
from datetime import date


class PadraoView(LoginRequiredMixin,View):
    login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'exercicios/home.html'
    nome_materia = ""
    
    def get(self, request, id=None, *args, **kwargs):
        if self.nome_materia == "":
            materias = Materia.objects.all()
            
        else:
            materias = Materia.objects.get(name = self.nome_materia)

        user = User.objects.get(id=request.user.id)
        num_exercises = Exercicios.objects.all().count()
        num_instances = ExercicioInstance.objects.filter(aluno=user).count()
        num_materias = Materia.objects.all().count()
        #materias = Materia.objects.all()

        # Available exercises (status = 'a')
        num_instances_available = ExercicioInstance.objects.filter(aluno=user).filter(status__exact='n').count()
        num_instances_answered = ExercicioInstance.objects.filter(
           Q(aluno=user)).filter(Q(status__exact='a')).count()
        

        #metodo GET
        context = {
        'num_exercises': num_exercises,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_materias':num_materias,   
        'num_instances_answered': num_instances_answered,   
        'materias': materias,  
    }
    
        return render(request, self.template_name,context)

class ResumoExerciciosView(LoginRequiredMixin,View):
    login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'exercicios/exe.html'
    paginate_by = 10
    context = {}
    materias = Materia.objects.all()
    def get(self, request, id=None, *args, **kwargs):
        tasks = ExercicioInstance.objects.filter(aluno=self.request.user).filter(status__exact='n').order_by('until_date')
        latest_question_list = Exercicios.objects.order_by('pub_date')[:4]
        #output = ', '.join([q.enunciado for q in latest_question_list])
        
        self.context = {
            'latest_question_list' : latest_question_list,
            'tasks': tasks,
            'materias': self.materias,
        }
        
        return render(request, self.template_name,self.context)


class ExercicioInstanceByUserListView(LoginRequiredMixin,ListView):
    model = ExercicioInstance
    template_name ='exercicios/exe.html'
    paginate_by = 10

    def get_queryset(self):
        return ExercicioInstance.objects.filter(aluno=self.request.user).filter(status__exact='n').order_by('until_date')

class ExerciciosView(LoginRequiredMixin,View):
    login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'exercicios/questoes.html'
    materias = Materia.objects.all()
    context={}
    def get(self, request, id=None, *args, **kwargs):
        
        if id is not None:
            
           exercicio = Exercicios.objects.get(pk=id)
           alternativas = exercicio.respostas_set.all()
           self.context = {
            'questao' : exercicio,
            'alternativas': alternativas,
            'materias': self.materias

        }
                
        return render(request, self.template_name,self.context)
    def post(self, request, id=None, *args, **kwargs):
        resposta_correta = (request.POST['resposta']).split(sep="|")
        
        exercicio = Exercicios.objects.get(id=int(resposta_correta[0]))
        resposta = Respostas.objects.get(id=int(resposta_correta[1]))

        teste = ExercicioInstance.objects.filter(exercicio=exercicio).filter(aluno=request.user)[0]
        teste.answer_date = date.today()
        if resposta.is_correct:
            teste.status = 'a'
        else:
            teste.status = 'e'
        teste.alternativa = resposta
        teste.save()

            
        return redirect('exercicios:resumo')

templates/exercicios/exe.html
{% extends "base.html" %}
{% load static %}
{% block headscripts %}
<style>
    nav span {
      color: #2B303A;
    }
    nav ul a {
      color: #2B303A;
    }
  </style>
{% endblock %}
{% block title %} Web Escola {% endblock%}

{% block content %}

<div class="col s11 m8 l9   ">


    <h1 class="espaco">Questões</h1>


    
        {% if tasks %}



        <div class="carousel">
            {% for question in tasks %}

            <a class="carousel-item" href="{% url 'exercicios:questoes' question.exercicio_id  %}">
                <div class="box">
                    <span class="gunmetal-text"> {{question}} </span>
                </div>
            </a>


            {% endfor %}
        </div>

        <p>
            Arraste para as laterais para ver outras perguntas.
        </p>
        <p>
            Clique na pergunta para respondê-la.
        
        </p>
        {% else %}
        <h2>Parabéns"</h2>
        <p>Você respondeu todas as perguntas.</p>


        {% endif %}
        <a class="voltar" href="{% url 'secretaria:inicial' %}" ><i class="small material-icons center">assignment_return</i></a>


    

    {% endblock %}

templates/exercicios/home.html
{% extends "base.html" %}
{% load static %}
{% block headscripts %}
<style>
    nav span {
      color: #2B303A;
    }
    nav ul a {
      color: #2B303A;
    }
  </style>
{% endblock %}
{%  block title %} Web Escola {% endblock%}

{%  block content %}
    <div class="col s12 m8 l9  allH ">

        <div class="row center-align allH ">
        
            <div class="col s12  allH ">
              
                <h1>Minhas Tarefas</h1>
                <p>Seja bem vindo a sua <em>Central de Tarefas</em>!</p>
                
                <p>Resumo:</p>
                <ul>
                    
                    <li><strong>Matérias Cadastradas:</strong> {{ num_materias }}</li>
                    <li><strong>Exercícios do Portal:</strong> {{ num_exercises }}</li>
                    <li><strong>Exercícios agendados:</strong> {{ num_instances }}</li>
                    <li><strong>Exercícios disponíveis para responder:</strong> {{ num_instances_available }}</li>
                    
                </ul>






                <div class="row center-align">
            
                    <a href="../" ><i class="small material-icons center">assignment_return</i></a>
                </div>
            </div>
            
        
    </div>
    </div>

  


    


{% endblock %}

templates/exercicios/materias.html
{% extends "base.html" %}
{% load static %}
{% block headscripts %}
<style>
    nav span {
      color: #2B303A;
    }
    nav ul a {
      color: #2B303A;
    }
  </style>
{% endblock %}
{%  block title %} Web Escola {% endblock%}

{%  block content %}

<div class="row">

    
    <div class="col  s12 m4 l3 azulzinho ">
        
        <div class="col s12 m12 l12">
            
            <div class="card horizontal">
                <div class="card-image">
                    <img src="https://lorempixel.com/100/190/abstract/4/">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <p>Todos Exercícios</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'exercicios:resumo' %}">Ver os exercícios</a>
                    </div>
                </div>
            </div>
        </div>
            
        {% for materia in materias %}  
        
        <div class="col s12 m12 l12">
            
            <div class="card horizontal">
                <div class="card-image">
                    <img src="https://lorempixel.com/100/190/abstract/4/">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <p>Exercícios de {{materia.name}}</p>
                    </div>
                    <div class="card-action">
                        <a href="#">Ver os exercícios</a>
                    </div>
                </div>
            </div>
        </div>

           
        {% endfor %}
    </div>
         

    {% block exercicios %} {% endblock %}

  </div>


    


{% endblock %}

templates/exercicios/questoes.html
{% extends "base.html" %}
{% load static %}
{% block headscripts %}
<style>
    nav span {
      color: #2B303A;
    }
    nav ul a {
      color: #2B303A;
    }
  </style>
{% endblock %}
{% load materializecss %}
{%  block title %} Web Escola {% endblock%}

{%  block content %}


    <div class="col s12 m8 l9   ">

        <div class="row center-align  ">
          <h1 class="espaco">Exercício {{questao.id}} </h1>

    
        
            <div class="col s12 center-align ">
              <h4 class="conquista">{{questao}}</h4>
                
                <form action="" method="post">
                    {% csrf_token %}
                    {% for q in alternativas %}
                    <p>
                      <label>
                        <input class="with-gap" name="resposta" value="{{questao.id}}|{{q.id}}" type="radio"  />
                        <span>{{q.resposta_texto}}</span>
                      </label>
                    </p>
                    

                    {% endfor %}

                    <button class="waves-effect waves-light  tomato btn-large" type="submit" type="submit"><i class="material-icons left">send</i>Enviar</button>
                </form>
                
                



            </div>
            <a class="voltar" href="{% url 'exercicios:resumo' %}" ><i class="small material-icons center">assignment_return</i></a>
            
        
    </div>
    
      </div>
    
    </div>
    

{% endblock %}


              
                