escolaWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('secretaria.urls', namespace='secretaria')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exercicios/', include('exercicios.urls',namespace='exercicios')),
    
]

exercicios/urls.py
from django.urls import path
from .views import PadraoView, ExerciciosView, ResumoExerciciosView, ExercicioInstanceByUserListView

app_name='exercicios'

urlpatterns = [
    path('', PadraoView.as_view(), name='inicial'),
    path('questoes/',ResumoExerciciosView.as_view(), name='resumo'),
    #path('questoes/',ExercicioInstanceByUserListView.as_view(), name='resumo'),
    path('questoes/<int:id>', ExerciciosView.as_view(), name='questoes'),
]

secretaria/urls.py
from django.urls import path
from .views import PadraoView,CadastraExercicioView, DashboardView


app_name = 'secretaria'

urlpatterns = [
    path('', PadraoView.as_view(), name='inicial'),
    path('novas-questoes/',CadastraExercicioView.as_view(), name='cadastra'),
    path('dashboard/',DashboardView.as_view(), name='dashboard'),
   # path('exercicios/', PadraoView.as_view(template_name = 'secretaria/exercicios.html'), name='exercicios'),
]

users/urls.py
from django.urls import path
from .views import PadraoView

app_name = 'users'

urlpatterns = [
    path('', PadraoView.as_view(), name='perfil'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link
    href="https://fonts.googleapis.com/css2?family=Klee+One&family=Merriweather:wght@300&family=Montserrat:wght@200&display=swap"
    rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>{% block title %} {% endblock%}</title>
    
    {% block headscripts %}

    {% endblock %}
</head>
<body >
  <div class="baseazul_cima"></div>
  <div class="baseazul_baixo">
    <p>© 2021 Escola Web</p>
  </div>
  <div class="navbar-fixed ">
  <nav>
    <div class="nav-wrapper cyellow gunmetal-text">
      <a href="#" class="brand-logo" >
        <img class="nav_img" src="{% static 'img\graduation-cap.png' %}" alt="chapeu de estudante">
        <span class="title_nav">Escola Web</span>
        
      
      </a>

      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <li><a class ="navbar-end navbar-item " href="{% url 'secretaria:inicial'%}">Inicial</a></li>
        
        {% if user.is_authenticated %}
      <li><a class ="navbar-end navbar-item " href="{% url 'exercicios:resumo'%}">Exercicios</a></li>  
      <li><a href="{% url 'users:perfil' %}">{{request.user.name}}</a></li>
      <li><a href="{% url 'logout'%}"><i class="small material-icons">exit_to_app</i></a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{ 'secretaria:inicial' }}">Entrar</a></li>
   {% endif %}
      </ul>
    </div>
  </nav>
</div>





<ul class="sidenav" id="mobile-demo">
    <li><a class ="navbar-end navbar-item " href="{% url 'secretaria:inicial'%}">Inicial</a></li>
    <li><a class ="navbar-end navbar-item " href="{% url 'exercicios:inicial'%}">Exercicios</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'users:perfil' %}">{{request.user.name}}</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}"><i class="small material-icons">exit_to_app</i></a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}
</ul>
      <!-- breadcrumps-->
      {% block breadcrumb %}

      {% endblock %}
     
      {% block content %}

      {% endblock %}
     <!--JavaScript at end of body for optimized loading-->
     <script type="text/javascript" src="{% static  'js/materialize.min.js' %}"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
     <script src="{% static 'js/main.js' %}"></script>
     {% block scripts %}

    {% endblock %}
</body>
</html>

templates/base_professor.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Klee+One&family=Merriweather:wght@300&family=Montserrat:wght@200&display=swap"
        rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>{% block title %} {% endblock%}</title>

    {% block headscripts %}

    {% endblock %}
</head>

<body>

    <div class="navbar-fixed ">
        <nav>
            <div class="nav-wrapper cyellow gunmetal-text">
                <a href="#" class="brand-logo">
                    <img class="nav_img" src="{% static 'img\graduation-cap.png' %}" alt="chapeu de estudante">
                    <span class="title_nav">Escola Web</span>


                </a>

                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

                <ul class="right hide-on-med-and-down">
                    <li><a class="navbar-end navbar-item " href="{% url 'secretaria:inicial'%}">Inicial</a></li>

                    {% if user.is_authenticated %}
                    <li><a class="navbar-end navbar-item " href="{% url 'exercicios:resumo'%}">Exercicios</a></li>
                    <li><a href="{% url 'users:perfil' %}">{{request.user.name}}</a></li>
                    <li><a href="{% url 'logout'%}"><i class="small material-icons">exit_to_app</i></a></li>
                    {% else %}
                    <li><a href="{% url 'login'%}?next={{ 'secretaria:inicial' }}">Entrar</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    <div class="baseazul_cima"></div>
    <div class="baseazul_baixo">
        <p>© 2021 Escola Web</p>
    </div>





    <ul class="sidenav" id="mobile-demo">
        <li><a class="navbar-end navbar-item " href="{% url 'secretaria:inicial'%}">Inicial</a></li>
        <li><a class="navbar-end navbar-item " href="{% url 'exercicios:inicial'%}">Exercicios</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'users:perfil' %}">{{request.user.name}}</a></li>
        <li><a href="{% url 'logout'%}?next={{request.path}}"><i class="small material-icons">exit_to_app</i></a></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
    </ul>
    <!-- breadcrumps-->
    {% block breadcrumb %}

    {% endblock %}

    <div class="row center-align allH">
        <div class="col lateral allH blue-grey ">


            <p class="menu-icon"><a href="{% url 'secretaria:inicial' %}"><i
                        class="small material-icons snow-text">home</i></a></p>

            <div class="divider"></div>


            <p class="menu-icon"><a href="{% url 'secretaria:cadastra' %}"><i
                        class="small material-icons snow-text">assignment</i></a>
            </p>

            <div class="divider"></div>

            <p class="menu-icon"><a href="{% url 'users:perfil' %}"><i
                        class="small material-icons snow-text">account_circle</i></a></p>

            <div class="divider"></div>

            <p class="menu-icon"><a href="{% url 'secretaria:dashboard' %}"><i
                        class="small material-icons snow-text">dashboard</i></a>
            </p>


        </div>

        <div class="col tela allH">
            {% block content %}

            {% endblock %}

        </div>




    </div>






    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static  'js/materialize.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts %}

    {% endblock %}
</body>

</html>